# Generated by Django 3.2.5 on 2021-08-22 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100, verbose_name='Produit')),
                ('price', models.FloatField(verbose_name='Prix')),
                ('description', models.TextField(blank=True, max_length=800, null=True, verbose_name='déscription')),
                ('additional_information', models.TextField(blank=True, max_length=800, null=True, verbose_name='Information additionnelle')),
                ('category', models.ForeignKey(blank=True, choices=[('M', 'Maquillage'), ('P_H', 'Parfum homme'), ('P_F', 'Parfum femme')], null=True, on_delete=django.db.models.deletion.CASCADE, to='site_project.item', verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_project.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('orderd_date', models.DateTimeField()),
                ('orderd', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='site_project.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
