# Generated by Django 3.2.5 on 2021-08-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_project', '0002_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('M', 'Maquillage'), ('P_H', 'Parfum homme'), ('P_F', 'Parfum femme')], null=True, on_delete=django.db.models.deletion.CASCADE, to='site_project.item', verbose_name='Catégorie'),
        ),
    ]
