# Generated by Django 3.2.5 on 2021-08-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_project', '0003_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('Maquillage', 'Maquillage'), ('Parfum homme', 'Parfum homme'), ('Parfum femme', 'Parfum femme')], null=True, on_delete=django.db.models.deletion.CASCADE, to='site_project.item', verbose_name='Catégorie'),
        ),
    ]
