# Generated by Django 3.2.5 on 2021-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_project', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Maquillage', 'Maquillage'), ('Parfum homme', 'Parfum homme'), ('Parfum femme', 'Parfum femme')], max_length=50, null=True, verbose_name='Catégorie'),
        ),
    ]
